### ISSUE TITLE
Can't use multiple items in the common, uncommon and rare item sections in the config

### ISSUE THREAD

**Issue by NJL5390** [mactso/HarderFarther#1]
When testing this mod lately for my modpack, I've noticed that when attempting to enter multiple items into the rare, common and uncommon item sections that the game either crashes or the drops don't work and the mobs just drop paper instead. When the config has just one item listed in each item section then it works fine.

From looking at the config I was unsure if the mod didn't support having multiple items in this section or if it was a bug causing it to not work. If this situation is the former then would I be able to request this functionality be added? If this situation is the latter then you can find more details about versions and crash logs below:

Forge Version: 36.1.13
Minecraft Version: 1.16.5
Harder Farther Version: 1.36.0.6
Crash Report (For when it crashed): https://pastebin.com/kt8rM6Fd
Latest Log (For when the mobs dropped Paper instead of the specified items in the config): [latest.log](https://github.com/mactso/HarderFarther/files/6385527/latest.log)

Something else that I though might interest you were these lines that I found from looking in the log above:

[15:57:26] [modloading-worker-8/WARN]: Bad item: minecraft:emerald, eidolon:arcane_gold_nugget, eidolon:soul_shard, eidolon:lead_nugget
[15:57:26] [modloading-worker-8/WARN]: Bad item: minecraft:diamond, eidolon:lesser_soul_gem, eidolon:arcane_gold_ingot, eidolon:lead_ingot, savageandravage:blast_proof_plating
[15:57:26] [modloading-worker-8/WARN]: Bad item: minecraft:netherite_scrap, eidolon:shadow_gem, majruszs_difficulty:end_shard, curios:ring, curios:knuckles, curios:amulet, curios:crown 

Correct me if I'm wrong but it seems like the game is trying to interpret them as just one item instead of multiple and maybe this is why it doesn't work?
![2021-04-27_16 01 37](https://user-images.githubusercontent.com/64381954/116264459-35767c80-a772-11eb-9517-33e70757f206.png)

**Comment by mactso** [comment]
Sorry for the delay.

I'll give this a look tonight!

With Best Regards,
Two Guys,
MacTso

**Comment by mactso** [comment]
Hi, sorry for the delay, I've tested this with Euidolon and it works.

However, I think you are using multiple items on each loot line and HF only supports one item.  Here's an example section that works:

	#Rare Loot Item
	itemRare = "minecraft:netherite_scrap"
	#Uncommon Loot Item
	itemUncommon = "minecraft:diamond"
	#Common Loot Item: 
	itemCommon = "eidolon:arcane_gold_nugget"


I think it is an interesting idea to support a little loot table for each line and I'll put that on the list for a future release.
